
name: 部署文档

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |
          sed -i 's|p\.trss\.me|pg.trss.me|' src/.vuepress/theme.ts
          pnpm run build
          > src/.vuepress/dist/.nojekyll

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 部署文档
          branch: gh-pages
          folder: src/.vuepress/dist
